- docs/headers/README.MD
- docs/headers/license.java
- docs/headers/license.script
> Added standard license headers

- files/launch/2.6.html
- files/launch/README.md
Part of the Browser Launch changes
> First version of quick start launch file

- files/launch/2.7.html
Will change the 2.6 one to advertise 2.7 once its released
> Added 2.7 browser launch file

- ZapVersions-2.7.xml
Right now this is a copy of the 2.6 one - all of them will need to be updated for the release
> Added 2.7 versions page

- files/launch/2.6.html
No French translation, but tbh that was just to prove it worked ;)
> Update the 2.6.0 start page to advertise 2.7.0

- docs/headers/license.java
- docs/headers/license.script
Update license.script and license.java for 2018
> 2018 Update

- files/launch/2.7.html
The toolswatch survey has closed
> Reverted to original message

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 10 of OpenAPI Support add-on.
> openapi: release version 10

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 24 of Script Console add-on.
> scripts: release version 24

- files/launch/2.7.html
They look ok according to Google Translate :)
Tool used to generate them is here: https://github.com/zaproxy/zap-extensions/pull/1325
Plan is to automate these PRs as per the other language files
> Updated translations from crowdin

- src/main/java/org/zaproxy/admin/CountDownloads.java
I use this for maintaining ZAP stats ;)
> Explicitly get the latest releases

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 30 of Active scanner rules add-on.
> ascanrules: release version 30

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 6 of Community Scripts add-on.
> communityScripts: release version 6

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 1 of Json view add-on.
> jsonview: release version 1

- build/build.xml
Thought it was as good a place as any to document this ;)
> Added notes for publishing translations of the user guide

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 7 of Context Alert Filters add-on.
> alertFilters: release version 7

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Beta:
- Invoke Applications version 9.
Alpha:
- Passive scanner rules (alpha) version 20.
> Release new versions of alpha/beta add-ons

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 15 of WebSockets add-on.
> websocket: release version 15

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 7 of DOM XSS Active scanner rule add-on.
> domxss: release version 7

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 21 of Active scanner rules (alpha) add-on.
> ascanrulesAlpha: release version 21

- src/main/java/org/zaproxy/admin/PendingAddOnReleases.java
List the add-ons without changes (new version but not yet changed) in a
different table.
> Differentiate add-ons without changes

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
It still has issues: zaproxy/zaproxy#2235
> Remove birtreports add-on from marketplace

- src/main/java/org/zaproxy/admin/CheckLatestReleaseNotes.java
- src/main/java/org/zaproxy/admin/CountDownloads.java
- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
- src/main/java/org/zaproxy/admin/HelpGenerator.java
- src/main/java/org/zaproxy/admin/HelpReportMissing.java
- src/main/java/org/zaproxy/admin/PendingAddOnReleases.java
Normalise the license header in all Java classes.
> Normalise license header

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 2 of Groovy scripting add-on.
> groovy: release version 2

- .travis.yml
Change Travis CI build configuration file to cache Gradle data.
> Enable cache in Travis CI builds

- build.gradle
- src/main/java/org/zaproxy/admin/AddOnsTask.java
- src/main/java/org/zaproxy/admin/PendingAddOnReleases.java
Update ZAP to latest version.
Change tasks to not use deprecated code.
> Update ZAP to 2.7.0

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 6 of Content Security Policy Scanner add-on.
> cspscanner: release version 6

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 7 of Community Scripts add-on.
> communityScripts: release version 7

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 10 of Python Scripting add-on.
> jython: release version 10

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 11 of OpenAPI Support add-on.
> openapi: release version 11

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 12 of Token generation and analysis add-on.
> tokengen: release version 12

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 12 of OpenAPI Support add-on.
> openapi: release version 12

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release initial version of Save XML Message add-on.
> savexmlmessage: initial release

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 16 of WebSockets add-on.
> websocket: release version 16

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 6 of Replacer add-on.
> replacer: release version 6

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 8 of Community Scripts add-on.
> communityScripts: release version 8

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 4 of Custom Report add-on.
> customreport: release version 4

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 7 of Code Dx Extension add-on.
> codedx: release version 7

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 17 of WebSockets add-on.
> websocket: release version 17

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 24 of Active scanner rules (beta) add-on.
> ascanrulesBeta: release version 24

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 18 of WebSockets add-on.
> websocket: release version 18

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 24 of Quick Start add-on.
> quickstart: release version 24

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 22 of Ajax Spider add-on.
> spiderAjax: release version 22

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
- Passive scanner rules version 23.
- Passive scanner rules (alpha) version 22.
> Release new versions of passive scanner add-ons

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java
Can be executed with the following command, e.g.:
`gradle updateDailyRelease --file=/path/to/ZAP_WEEKLY_D-2018-09-04.zip`
The task is configured to update all ZapVersions.xml files.
> Add task to update ZapVersions with daily release

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 22 of Active scanner rules (alpha) add-on.
> ascanrulesAlpha: release version 22

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 32 of Active scanner rules add-on.
> ascanrules: release version 32

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
- Form Handler version 2.
- Replacer version 7.
> Release new versions of add-ons

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
- Linux WebDrivers version 7;
- MacOS WebDrivers version 7;
- Windows WebDrivers version 7.
> Release WebDrivers add-ons

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 5 of Access Control Testing add-on.
> accessControl: release version 5

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 28 of Zest add-on.
> zest: release version 28

- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
The API clients have their own release notes.
> Ignore API Client issues for release notes

- ZapVersions-dev.xml
Release version 0.1.0 of HUD add-on to dev marketplace.
> hud: release version 0.1.0

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 14 of Selenium add-on.
> selenium: release version 14

- files/launch/2.8.html
- files/launch/dev.html
Right now dev and 2.8 are the same - suggestions as to how to improve them appreciated :)
cc @kingthorin @dscrobonia
> Add launch files for dev and 2.8

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Release version 12 of Wappalyzer - Technology Detection add-on.
> wappalyzer: release version 12

- ZapVersions-2.7.xml
- ZapVersions-dev.xml
Encode character `>` and sort add-ons by ID.
> Normalise ZapVersions.xml files

- files/news/2_8.xml
- files/news/dev.xml
Configuration file to be used for ZAP news items.
Example UI:
This is the planned first item but the URL may change, eg if we write a better landing page :)
> First news page

- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-dev.xml
- ZapVersions.xml
> Updated for the weekly release

- src/main/java/org/zaproxy/admin/CheckLatestReleaseNotes.java
- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
Dont know if we'll need this going forwards but these changes were needed for the 2.8.0 release notes.
> Added ignore tags and misc changes

- ZapVersions-2.8.xml
- build.gradle.kts
This will need updating with the 2.8.0 downloads and latest add-ons when they are available.
> Added ZapVersions-2.8.xml

- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-dev.xml
- ZapVersions.xml
Update ZapVersions files with core release.
> Release 2.8.0

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Remove the add-on from dev and 2.8, that version is only for 2.7.0
release.
> Remove old Core Language Files

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Release version 9 of DOM XSS Active scanner rule add-on.
> domxss: release version 9

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> allinonenotes: release version 1

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> regextester: release version 1

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Release version 6 of Export Report add-on.
> exportreport: release version 6

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
- FuzzDB files version 5;
- FuzzDB Web Backdoors version 1.
> Release FuzzDB add-ons

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Release version 13 of OpenAPI Support add-on.
> openapi: release version 13

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> Release websockets

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Release version 0.5.0 of HUD add-on.
> hud: release version 0.5.0

- files/launch/2.6.html
- files/launch/2.7.html
- files/launch/2.8.html
- files/launch/dev.html
Use the new dir path to the images in zaproxy for launch page.
Related to zaproxy/zaproxy#5369.
> Fix links to images

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> Release the HUD

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> wappalyzer: release version 13

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
Release version 8 of Code Dx add-on.
> codedx: release version 8

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
- Custom Report version 5;
- SAML Extension version 8.
> Release add-ons

- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> alertFilters release version 9

- ZapVersions-2.9.xml
- build.gradle.kts
In preperation for the 2.9.0 release
> Add ZapVersions-2.9

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> pscanrulesBeta: release version 20

- files/news/2_8.xml
- files/news/dev.xml
> News item: ZAP in Ten

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 14 of OpenAPI Support add-on.
> openapi: release version 14

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 30 of Zest add-on.
> zest: release version 30

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> scanrule releases

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> wappalyzer release version 15

- build.gradle.kts
- src/test/java/org/zaproxy/admin/ValidateZapVersionsXmlTest.java
Use only AssertJ for assertions.
Update AssertJ to 3.14.0.
> Remove Hamcrest

- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Re: https://github.com/zaproxy/zaproxy/issues/5781
> neonmarker: release v1.1.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release the HUD for 2.9

- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
- ZapVersions.xml
Update ZapVersions for ZAP 2.9.0.
> Update main release to 2.9.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 32 of Zest add-on.
> zest: release version 32

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> wappalyzer: release version 16

- .gitignore
Ignore Eclipse's bin dir also in buildSrc.
> Ignore bin dir in buildSrc

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 9 of Community Scripts add-on.
Release version 2 of FuzzDB Web Backdoors add-on.
> Release Community Scripts and FuzzDB Web Backdoors

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release new versions of the HUD and Quickstart

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> pscanrules: release version 27

- .github/workflows/update-website.yml
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateWebsite.java
Checkout the whole website repo to ensure there's no missing history
(which could lead to rejection of the pushed branch).
Check if the pull request is still open (to updated it, force push).
> Tweak update-website workflow and task

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Updated for wappalyzer v17 release
> wappalyzer: release version 17

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release selenium 15.2.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Neonmarker: release version 1.2.0

- files/news/2_9.xml
- files/news/dev.xml
Wasnt confident about the French translation so didnt include that.
> News: baseline github actions

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 1.0.0 of Common Library add-on.
> commonlib: release version 1.0.0

- scripts/generate_alert_pages.js
This should be automated at some stage, but putting here so it wont get
lost.
Feel free to suggest a better location...
> Added file for generating the alert pages

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> pscanrules (all), ascanrules (all), retire, encoder: releases

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 16 of OpenAPI Support add-on.
> openapi: release version 16

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> wappalyzer: release version 19

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> reflect: release version 0.0.8

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Add the URLs already set in the add-ons but not yet released, to allow
to automatically generate the data for the website sooner.
> Add info and repo URLs to the add-ons

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> wappalyzer and retire releases

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Remove old fuzzdbwebbackdoors entries
> fuzzdb add-ons: relase v7 and v3

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 20.1.0 of Wappalyzer - Technology Detection add-on.
> wappalyzer: release version 20.1.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> imagelocationscanner: release version 2

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 2 of ViewState add-on.
> viewstate: release version 2

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 4 of Requester add-on.
> requester: release version 4

- scripts/generate_alert_pages.js
Cope with empty CWE / WASC ids and ignore specified alerts.
> Generate alert fixes

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release ascanrulesBeta v29

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> ascanrulesBeta: Release version 30

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release latest webdrivers

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Addon releases: ascanrules, commonlib, retire, and wappalyzer

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> HUD v0.11.0

- .github/workflows/alert-docs.yml
- scripts/generate_alert_pages.js
I've tested the scripting in isolation but not all together in the workflow :/
> Generate alert docs for website

- .github/workflows/alert-docs.yml
> More workflow tweaks

- .github/workflows/alert-docs.yml
> Set base branch in PR

- scripts/generate_alert_pages.js
I'll remove the existing example alert pages ina PR on the website.
> Ignore more example alerts

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Signed-off-by: Kingthorin <kingthorin@users.noreply.github.com>
> a & p scanrulesAlpha: releases

- scripts/generate_alert_pages.js
Part of https://github.com/zaproxy/zaproxy/issues/6119
Handles changes in https://github.com/zaproxy/zap-extensions/pull/2517
> Changed to use example alerts

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Signed-off-by: ricekot <ricekot@gmail.com>
> graphql: Release version 0.1.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> ascanrulesBeta: release 31

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Signed-off-by: Kingthorin <kingthorin@users.noreply.github.com>
> JWT: Release v1

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 13.0.1 of Fuzzer add-on.
> fuzz: release version 13.0.1

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release kotlin add-on

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Signed-off-by: Kingthorin <kingthorin@users.noreply.github.com>
> Encoder: Release version 0.3.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> wappalyzer and neonmarker releases

- src/main/java/org/zaproxy/admin/CountDownloads.java
- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
> Update for 2.10 and issue links

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release Access Control v6

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release HUD 0.12.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release Retire 0.5.0

- scripts/generate_alert_pages.js
> Update alert generation script

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release webdrivers with geckodriver 0.28.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 23.2.0 of Ajax Spider add-on.
> spiderAjax: release version 23.2.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 29 of Passive scanner rules (alpha) add-on.
> pscanrulesAlpha: release version 29

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Release GraalJS 0.1.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> Updated webdrivers to support ChromeDriver 87.0.4280.20

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> pscanrulesBeta: release version 23

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Signed-off-by: ricekot <ricekot@gmail.com>
> graphql: release version 0.2.0

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> pscanrules: release version 30

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
> ascanrules: Releases

- files/news/2_9.xml
- files/news/dev.xml
> News - ZAP videos

- ZapVersions-2.9.xml
- ZapVersions-dev.xml
Release version 33 of Zest add-on.
> zest: release version 33

- files/news/2_9.xml
- files/news/dev.xml
> News: 2.10.0 candidate release

- ZapVersions-2.10.xml
- build.gradle.kts
I'll start releasing the changed add-ons on 2.10 once this has been merged...
> Add 2.10 version file

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Publish 2.10 add-ons - phase 1

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Publish 2.10 add-ons - phase 3

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Publish 2.10 add-ons - phase 4

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release version 4 of SOAP Support add-on.
> soap: release version 4

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Publish 2.10 help

- files/news/2_10.xml
> Add the 2.10 news page

- ZapVersions-2.10.xml
- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
- ZapVersions.xml
- files/news/2_10.xml
- files/news/2_8.xml
- files/news/2_9.xml
> 2.10.0 release

- ZapVersions-2.10.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
As per https://github.com/zaproxy/zaproxy/issues/6367 and https://github.com/zaproxy/zap-extensions/pull/2657
> Remove cmss add-on

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release Scripts and WebSockets

- files/news/2_10.xml
- files/news/dev.xml
> News - questionnaire

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> jwt: Release version 1.0.1

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Signed-off-by: ricekot <ricekot@gmail.com>
> soap: Release version 5

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release version 32 of Passive scanner rules add-on.
> pscanrules: release version 32

- files/news/2_10.xml
- files/news/dev.xml
> News: ZAPCon CFP

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release Pscanrules v33

- files/news/2_10.xml
- files/news/dev.xml
> News - link directly to zapcon.io

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release version 30 of Passive scanner rules (alpha) add-on.
> pscanrulesAlpha: release version 30

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> encoder: Release v0.5.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> reflect: Release v0.0.10

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> reflect: Release v0.0.11

- files/news/2_10.xml
- files/news/dev.xml
> News: ZAPCon speakers announced

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> wappalyzer: Release v21.1.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release automation related add-ons

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
And corrected the release notes in dev, dont know why that was different ;)
> Added missing urls

- files/news/2_10.xml
- files/news/dev.xml
> News - reporting competition

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release reports v0.1.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> retire: release version 0.7.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Signed-off-by: ricekot <ricekot@gmail.com>
> automation: Release version 0.1.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
GraphQL Support version 0.3.0;
SOAP Support version 6.
> Release SOAP and GraphQL add-ons

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Show the help URL in the website earlier.
> Add help URL to SOAP add-on

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release automation and reporting 0.2.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
- Linux WebDrivers version 28;
- MacOS WebDrivers version 27;
- Windows WebDrivers version 28.
>  Release WebDrivers add-ons

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release version 34 of Zest add-on.
> zest: release version 34

- files/news/2_10.xml
- files/news/dev.xml
> New item: The reporting competition is still open

- ZapVersions-2.10.xml
- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-2.9.xml
- ZapVersions-dev.xml
- ZapVersions.xml
> Update for the weekly release

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release reports 0.3.0

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release ascanrules and commonlib

- .github/workflows/update-daily-release.yml
- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/CreatePullRequest.java
- buildSrc/src/main/java/org/zaproxy/gradle/CustomXmlConfiguration.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java
- buildSrc/src/main/kotlin/org/zaproxy/gradle/GitHubRepo.kt
- buildSrc/src/main/kotlin/org/zaproxy/gradle/GitHubUser.kt
The workflow will update the weekly release on repository dispatch.
> Add workflow to update weekly release

- buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java
The from URL is not needed when updating from file.
> Make from URL optional when updating weekly

- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateZapVersionWebsiteData.java
Update the ZAP version in main release data files (ones shown in
downloads page).
> Update main release website data files

- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/AbstractGenerateWebsiteReleaseData.java
- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteAddonsData.java
- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteMainReleaseData.java
- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteWeeklyReleaseData.java
- buildSrc/src/main/java/org/zaproxy/gradle/SendRepositoryDispatch.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateMainZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateWebsite.java
- Simplify handling of user/repo data
- Reduce boilerplate code
> Tidy up tasks

- .github/workflows/update-main-release.yml
- build.gradle.kts
The workflow will update the main release on repository dispatch.
> Add workflow to update main release

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release version 8 of Tips and Tricks add-on.
> tips: release version 8

- .github/workflows/update-main-release.yml
- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/CreateNewsMainRelease.java
Create a news file (if needed) and news entries on main release.
> Create news file and news entries on main release

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
> Release Fuzz 13.2.0

- .github/workflows/update-add-on-release.yml
- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/AbstractUpdateZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/AddOnReleaseData.java
- buildSrc/src/main/java/org/zaproxy/gradle/AddOnZapVersionsUpdater.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateAndCreatePullRequestAddOnRelease.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateZapVersionsEntries.java
The workflow will update the add-on releases on repository dispatch.
Extract common code to avoid duplication between manual and automatic
task.
> Add workflow to update add-on releases

- .github/workflows/update-add-on-release.yml
Split the runs into their own steps.
> Fix add-on release workflow

- .github/workflows/update-add-on-release.yml
Correctly set the client payload into the env variable.
> Fix client payload processing in release workflow

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/AddOnZapVersionsUpdater.java
- buildSrc/src/main/java/org/zaproxy/gradle/DownloadReleasedAddOns.java
- buildSrc/src/main/java/org/zaproxy/gradle/GenerateReleaseStateLastCommit.java
- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsitePages.java
- buildSrc/src/main/java/org/zaproxy/gradle/ReleaseState.java
- buildSrc/src/main/java/org/zaproxy/gradle/TaskUtils.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateAndCreatePullRequestAddOnRelease.java
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateZapVersionsEntries.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/HelpSetFactory.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/PageFrontMatter.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/SourceImage.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/SourcePage.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/TocTree.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/Utils.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/WebsitePageGenerationException.java
- buildSrc/src/main/java/org/zaproxy/gradle/website/WebsitePageGenerator.java
- src/main/addons-help-website.txt
Add tasks and update build to generate the website pages when the add-ons are released.
> Generate website pages of released add-ons

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Mention all changes of the latest version.
> Update changes of Wappalyzer add-on

- buildSrc/src/main/java/org/zaproxy/gradle/CreatePullRequest.java
Include untracked files when creating the pull requests (e.g. new help
pages).
> Create pull request with all files

- buildSrc/src/main/java/org/zaproxy/gradle/CreatePullRequest.java
Only call git add if there are new files.
> Guard against no untracked files

- files/news/2_10.xml
- files/news/dev.xml
> News: Simon's AMA

- files/news/2_10.xml
- files/news/dev.xml
> News: Usage Questionnaire

- .github/workflows/crowdin-build-translations.yml
- .github/workflows/crowdin-download-translations.yml
Disable scheduling until the issues found are addressed.
> Disable scheduled Crowdin workflows

- .github/workflows/crowdin-build-translations.yml
- .github/workflows/crowdin-download-translations.yml
Enable scheduling as the issues found are now addressed.
> Enable scheduled Crowdin workflows

- ZapVersions-2.10.xml
- ZapVersions-dev.xml
Release the following add-ons:
- OAST Support version 0.2.0
> Release add-on(s)

- scripts/generate_alert_pages.js
Depends on https://github.com/zaproxy/zap-extensions/pull/3089 
In theory it should work without those changes (just wont generate the websocket ones) but might as well wait for that to be merged before merging this.
I've also removed the "Scan Rule" from the Type column - the deprecated alerts will have to be updated manually, but I'll submit a PR for that after we've merged the one this generates...
> Support websocket pscan alerts

- scripts/generate_alert_pages.js
This worked fine locally but then failed in the github action, of course :P
> Wrap ws calls in try catch block

- scripts/generate_alert_pages.js
> Use main branch for zap-extension links

- scripts/generate_alert_pages.js
> Fix link for FileUploadScanRule

- .github/workflows/event-docs.yml
- scripts/generate_events_page.js
Depends on https://github.com/zaproxy/zaproxy/pull/6804
> Add script and action for updating events page

- scripts/generate_events_page.js
> Fix events script links

- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
> Update milestone number for 2.11.0 release notes

- files/news/2_10.xml
- files/news/dev.xml
> News: OWASP 20th Anniversary Event - ZAP 2.11.0

- ZapVersions-2.11.xml
- build.gradle.kts
This is a copy of the 2.10 one but with the 'old' reporting add-ons removed.
> Add 2.11.0 versions file

- files/news/2_10.xml
- files/news/2_11.xml
- files/news/dev.xml
Not to be merged until we've actually done the release and the download link has been updated ;)
> New: 2.11 RC

- scripts/generate_alert_pages.js
> Add support for alert tags

- files/news/2_11.xml
- files/news/dev.xml
> News: ZAPCon 2022 Call for Speakers

- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/org/zaproxy/gradle/ZapTask.kt
- gradle/wrapper/gradle-wrapper.properties
Update Gradle Wrapper and build to 7.2.
Update plugins to latest versions.
Apply format changes to build files.
> Update Gradle to 7.2

- .github/workflows/alert-docs.yml
- scripts/generate_alert_pages.js
Corresponding website PR: https://github.com/zaproxy/zaproxy-website/pull/665
> Support alert tag pages

- src/main/addons-help-website.txt
> Add network for website help pages

- scripts/generate_alert_pages.js
Signed-off-by: Akshath Kothari <github@ricekot.com>
> Don't override example alert tags

- files/news/2_11.xml
- files/news/dev.xml
> News: Contribute

- files/news/2_11.xml
- files/news/dev.xml
> News: ZAPCon lineup published

- files/news/2_11.xml
- files/news/dev.xml
Depends on https://github.com/zaproxy/zaproxy-website/pull/784
> News 27 - ZAPCon 2022 schedule

- scripts/generate_alert_pages.js
Missed from https://github.com/zaproxy/zap-admin/pull/725 :/
> Remove missed date/lastmod fields

- scripts/generate_alert_pages.js
> Alert page gen: sort the tags

- files/news/2_11.xml
- files/news/dev.xml
> News: ZAPCon videos on YouTube

- .github/workflows/alert-docs.yml
> Alert pages action: add new pages

- ZapVersions-2.11.xml
- src/main/java/org/zaproxy/admin/HelpGenerator.java
Update the HelpGenerator, ZapVersions-2.11.xml, and ZapVersions-dev.xml.
Related to zaproxy/zaproxy#4732
> chore: Standardize on the use of "status" vs "quality"

- src/main/addons-help-website.txt
> Add planned add-on packs

- scripts/generate_alert_pages.js
To fix https://github.com/zaproxy/zaproxy-website/runs/7351192553?check_suite_focus=true
> Alert page script - quote alert names

- src/main/addons-help-website.txt
Related to zaproxy/zaproxy#3113
> Add spider to add-on help publishing list

- files/news/2_11.xml
- files/news/dev.xml
> News: Jit Platinum Support

- .github/workflows/alert-docs.yml
This can also be updated by the script.
Example failure: https://github.com/zaproxy/zap-admin/actions/runs/3189626952/jobs/5203650296
> Alert job - add alerttags.yml

- files/news/2_11.xml
- files/news/dev.xml
> News: help zaproxy get 10k stars

- ZapVersions-2.12.xml
- build.gradle.kts
- files/news/2_12.xml
> Add 2.12 files

- build.gradle.kts
- src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
Use the milestone for 2.12.
Print the issue title HTML escaped, also, extract a method to print the issues.
> Update milestone for release notes

- build.gradle.kts
> Switch to 2.12

- scripts/generate_alert_pages.js
> Fix alert page gen script

- scripts/generate_alert_pages.js
To generate the techtags for https://github.com/zaproxy/zaproxy-website/pull/1437
> Generate alert tech tags

- ZapVersions-2.12.xml
- ZapVersions-dev.xml
Also add info URL for the add-on.
> Release Levo.ai add-on v0.2.0

- files/news/2_12.xml
- files/news/dev.xml
> News: 2022 in review

- files/news/2_12.xml
- files/news/dev.xml
Text ok?
Better suggestions always appreciated!
> New: Selenium auth blog post

- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteAddonsData.java
Update the notation used to read the properties, the configuration is no longer using XPath.
> Fix website related task

- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteMainReleaseData.java
Get the (for now optional) macOS aarch64 download from the main release to include it in the website.
Tweak description of existing macOS installer to include the arch.
> Include macOS aarch64 download in website data

- .github/workflows/alert-docs.yml
- .github/workflows/event-docs.yml
> Update ZAP Docker images

- ZapVersions-2.11.xml
- ZapVersions-2.12.xml
- ZapVersions-2.13.xml
- ZapVersions-2.4.xml
- ZapVersions-2.5.xml
- ZapVersions-2.6.xml
- ZapVersions-2.7.xml
- ZapVersions-2.8.xml
- ZapVersions-dev.xml
> Update Crowdin links

- buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteMainReleaseData.java
Add common names before the arch.
Close zaproxy/zaproxy-website#2043.
> Update desc of macOS dists

- scripts/generate_alert_pages.js
Replace `Control` singleton with the injected variable `control`.
> Remove singleton usage in helper script

- .github/workflows/alert-docs.yml
- .github/workflows/event-docs.yml
- build.gradle.kts
Change the default branch to main.
> Update website's default branch

- scripts/generate_alert_pages.js
Generate client alert pages and help links.
Part of https://github.com/zaproxy/zaproxy/issues/8189
> Alert gen: client alerts and help links

- scripts/generate_alert_pages.js
Was changed in the review :wink:
> Alert gen - fix client method name

- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateGettingStartedWebsitePage.java
Update the page and copy the PDF file when the gettingStarted add-on is released.
> Update getting started website page and PDF

- src/main/crowdin-tasks.yml
Do not copy translations of newer locale that does not have any.
---
WIP pending update of the Crowdin plugin in the respective repos.
> Filter locale from translation deployment

- ZapVersions-2.15.xml
- ZapVersions-dev.xml
> Link to source of reflect add-on

- .github/workflows/handle-release.yml
- build.gradle.kts
- buildSrc/src/main/java/org/zaproxy/gradle/UpdateFlathubData.java
Add task to update the Flathub repo on main releases.
> Update Flathub on main releases

- .gitignore
Ignore files that are created when running the build.
> Ignore Kotlin build related files

- build.gradle.kts
Send repo dispatch to the zaproxy repo to release it on main releases.
---
Uses zaproxy/zaproxy#8907.
> Trigger release of snap package

- scripts/generate_alert_pages.js
Ensure all alert data is generated (e.g. help link), as the graal.js engine does not use the default methods.
> Update WebSocket Passive Rules alert generation
