zaproxy/zap-admin

.classpath
build.gradle
src/main/java/org/zaproxy/admin/PendingAddOnReleases.java

Change PendingAddOnReleases to use the ZapVersions file of 2.6 release,
also, include the period since the last release for each add-on.
Bump Java version to 8, easier to handle date calculations.

Update pending add-on releases to 2.6

---

build.gradle

Update ZAP jar to latest version (2.6.0), used by the "admin" tasks.

Update ZAP jar to latest version

---

src/main/java/org/zaproxy/admin/PendingAddOnReleases.java

Change PendingAddOnReleases to read the status from the manifest of the
add-ons (instead of hardcoded per branch, which might not be correct).

Update pending add-on releases status read

---

src/main/java/org/zaproxy/admin/PendingAddOnReleases.java

Change PendingAddOnReleases to use the ZapVersions file of 2.7 release.

Update pending add-on releases to 2.7

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

ZAP 2.7.0 and dev builds support SNI by default.
Refs:
- zaproxy/zaproxy#3899;
- zaproxy/zap-extensions#1228.

Remove SNI Terminator from 2.7/dev

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Release:
- Active scanner rules version 29;
- Ajax Spider v21;
- Passive scanner rules version 22;
- Quick Start version 23.
Beta:
- Active scanner rules (beta) version 23;
- Passive scanner rules (beta) version 18;
- Python scripting version 9;
- Replacer version 5;
- Script Console version 23;
- Zest - Graphical Security Scripting Language version 27.

Release new versions of release/beta add-ons

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Release:
- Active scanner rules version 31.
Alpha:
- Content Security Policy Scanner version 5.

Release new versions of release/alpha add-ons

---

docs/headers/README.MD
docs/headers/license.java
docs/headers/license.script

Remove white spaces at the end of the lines and in empty lines and
remove last empty line (not part of the header).
Replace the year with a token, so that it does not require update the
headers each year (it's up to the tool or user to replace it with the
current one). Update README to mention that.

Tidy up license headers

---

src/main/java/org/zaproxy/admin/AddOnsTask.java
src/main/java/org/zaproxy/admin/HelpReportMissing.java
src/main/java/org/zaproxy/admin/PendingAddOnReleases.java

Change HelpReportMissing to use the same logic as PendingAddOnReleases,
which takes into account the actual status of the add-ons (as declared
in the corresponding ZapAddOn.xml file).
Extract common code, so that it can be reused by HelpReportMissing and
PendingAddOnReleases.

Correct task that reports add-ons with no help

---

.classpath
build.gradle
src/test/java/org/zaproxy/admin/ValidateZapVersionsXmlTest.java

Add test to assert that ZAP is able to parse/load the ZapVersions.xml
files (current version, dev, and without add-ons).

Validate ZapVersions.xml files

---

src/test/java/org/zaproxy/admin/ValidateZapVersionsXmlTest.java

Change ValidateZapVersionsXmlTest to include the name of the file being
tested in the assertion, easier to notice which file is failing.

Include file name in test assertions

---

src/test/java/org/zaproxy/admin/ValidateZapVersionsXmlTest.java

Change ValidateZapVersionsXmlTest to assert that the ZapVersions files
are found, to provide a better error message (than a NPE). Also, obtain
the files in their own methods to avoid failing all tests if one is
missing and tweak the creation of the path to also work in Windows.

Assert ZapVersions files are found

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Release version 1.1.1 of Attack Surface Detector add-on.
For zaproxy/zaproxy#4670.

attacksurfacedetector: release version 1.1.1

---

ZapVersions-2.4.xml
ZapVersions-2.5.xml
ZapVersions-2.6.xml
ZapVersions-2.7.xml
ZapVersions-dev.xml
ZapVersions.xml

Use same character for indentation (spaces instead of mixed spaces and
tabs) and sort add-ons by ID.
This makes it more consistent and reliable when adding or updating
add-on entries programmatically (e.g. build tasks).

Normalise ZapVersions.xml files

---

build/build.xml

Change Crowndin configuration to place the core files (zaproxy and
zap-core-help) under a top level directory named core, to organise
better all the files.

Move core files to core directory in Crowdin

---

build.gradle.kts

Add Error Prone dependency to latest version, for stable builds.

Use specific Error Prone version

---

build.gradle.kts
src/test/java/org/zaproxy/admin/VerifyCoreZapVersionsEntries.java

Add test to verify that the core entry contains the expected elements
and that the values are the same for all files.

Verify ZapVersions' core entry

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

- Requester version 3.
- TLS Debug version 3.
---
Related to zaproxy/zaproxy#5056, with this release all add-ons in the marketplace have the status declared in the manifest.

Release new versions of alpha add-ons

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Release version 1.1.2 of Attack Surface Detector add-on.
For zaproxy/zaproxy#5043.

attacksurfacedetector: release version 1.1.2

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

- JxBrowser (core) version 12;
- JxBrowser (Linux 64) version 10;
- JxBrowser (Mac OS) version 10;
- JxBrowser (Windows) version 10;
- JxBrowser (Windows 64) version 3.

Release JxBrowser add-ons

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Release version 1.1.4 of Attack Surface Detector add-on.
For zaproxy/zaproxy#5229.

attacksurfacedetector: release version 1.1.4

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

The SOAP Scanner add-on is not working correctly.
From zaproxy/zaproxy#4866.

soap: remove from marketplace

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/CustomXmlConfiguration.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java

The task, `updateAddOnRelease`, updates the ZapVersions files with an
add-on available in the local file system:
`--file=/path/add-on.zap --downloadUrl=https://example.com/add-on.zap`
or, from a remote location:
`--url=https://example.com/add-on.zap`
The download URL defaults to the specified URL.
The task is configured to update dev and 2.7.

Add task to update ZapVersions with an add-on

---

ZapVersions-2.7.xml
ZapVersions-dev.xml

Per: `...\zap-admin>gradlew updateAddOnRelease --url=https://github.com/zaproxy/zap-extensions/releases/download/httpsInfo-v12/httpsInfo-alpha-12.zap`

Update for HttpsInfo v12 release

---

build.gradle.kts

Use SHA256 instead of SHA1 for improved checks.

Update checksum algorithm for add-ons and weekly

---

build.gradle.kts
gradle/travis-ci.gradle.kts

Use full format to output the stack trace when the ZapVersions
validations fail, to make it easier to know where it's failing.

Include test stack trace when running in Travis CI

---

ZapVersions-2.8.xml
ZapVersions-dev.xml
build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java

Release add-ons included in 2.8.0 and related ones:
- Active scanner rules version 33;
- Active scanner rules (beta) version 25
- Active scanner rules (alpha) version 24;
- Advanced SQLInjection Scanner version 13;
- Ajax Spider version 23.0.0;
- Context Alert Filters version 8;
- Diff version 9;
- DOM XSS Active scanner rule version 8;
- Forced Browse version 8;
- Fuzzer version 11;
- Getting Started with ZAP Guide version 10;
- Help - English version 9;
- HUD - Heads Up Display version 0.4.0;
- Import files containing URLs version 6;
- JxBrowser (core) version 14;
- JxBrowser (Linux 64) version 12;
- JxBrowser (Mac OS) version 12;
- JxBrowser (Windows) version 12;
- JxBrowser (Windows 64bits) version 5;
- Linux WebDrivers version 10;
- MacOS WebDrivers version 10;
- Passive scanner …

Release add-ons

---

build.gradle.kts

Change `updateAddOnRelease` task to no longer update 2.7, now targeting
just latest release.

Update add-ons only for 2.8 and dev

---

build.gradle.kts

The version 2.7 was accidentally added in a previous change...

Remove 2.7 from add-on update task

---

ZapVersions-2.8.xml
ZapVersions-dev.xml

Since the CSP Scanner is now release and part of the main pscan rules package (https://github.com/zaproxy/zap-extensions/releases/pscanrules-v24) the separate addon may as well be un-published to prevent occurrences of:

Un-publish CSP Scanner

---

ZapVersions-2.8.xml
ZapVersions-dev.xml

Release version 14 of Wappalyzer - Technology Detection add-on.

wappalyzer: release version 14

---

build.gradle.kts
src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java
src/main/java/org/zaproxy/admin/HelpGenerator.java

Change `GenerateReleaseNotes` to obtain the issues from the milestone
number (using an API client).
Address deprecations in `HelpGenerator`, required by (transitive) update
of Apache Commons IO library.

Use milestone for release notes

---

build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/UpdateMainZapVersionsEntries.java

Can be executed with the following command, e.g.:
`gradle updateMainRelease --release=2.9.0`
The task is configured to update all ZapVersions.xml files.

Add task to update ZapVersions with main release

---

build.gradle.kts
src/test/java/org/zaproxy/admin/ValidateZapVersionsXmlTest.java
src/test/java/org/zaproxy/admin/VerifyCoreZapVersionsEntries.java

Add dependency on JUnit 5 and remove JUnit 4.
Change tests to use new annotations/imports and parameterized tests.

Run tests with JUnit 5

---

build.gradle.kts

Otherwise 2.8 users will get a flood of add-on updates as we regenerate them for 2.9

No longer update the 2.8 marketplace

---

ZapVersions-2.9.xml
ZapVersions-dev.xml

- Active scanner rules version 34;
- Ajax Spider version 23.1.0;
- Alert Filters version 10;
- Diff version 10;
- Directory List v1.0 version 4;
- Forced Browse version 9;
- Fuzzer version 12;
- Getting Started with ZAP Guide version 11;
- Help - English version 10
- Import files containing URLs version 7;
- Invoke Applications version 10;
- Linux WebDrivers version 16;
- MacOS WebDrivers version 15;
- Online menus version 7;
- OpenAPI Support version 15;
- Passive scanner rules version 26;
- Quick Start version 27;
- Replacer version 8;
- Reveal version 3;
- Save Raw Message version 5;
- Save XML Message version 0.1.0;
- Script Console version 26;
- Selenium version 15.1.0;
- Tips and Tricks version 7;
- WebSockets version 21;
- Windows WebDrivers version 16;
- Zest - Graphical Security …

Release add-ons for 2.9.0

---

build.gradle.kts

Link to the site instead of the wiki when updating the main release.

Update the URL for the release notes

---

.github/workflows/update-website.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/AbstractGenerateWebsiteReleaseData.java
buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteMainReleaseData.java
buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteWeeklyReleaseData.java
buildSrc/src/main/java/org/zaproxy/gradle/ReleaseData.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateWebsite.java

Update weekly and main release website data when the ZapVersions files
are changed.
The GitHub Action will create a pull request (using @zapbot) with the
changes.

Update zaproxy-website on release changes

---

.github/workflows/update-website.yml
ZapVersions.xml

Use correct syntax to pass the parameter to the action.
Add space to ZapVersions.xml file to trigger the workflow.

Fix update-website workflow

---

ZapVersions-2.9.xml
ZapVersions-dev.xml

Retire.js: release version 0.3.1

---

.github/workflows/handle-release.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/GenerateReleaseStateLastCommit.java
buildSrc/src/main/java/org/zaproxy/gradle/HandleWeeklyRelease.java
buildSrc/src/main/java/org/zaproxy/gradle/ReleaseState.java
buildSrc/src/main/java/org/zaproxy/gradle/SendRepositoryDispatch.java
buildSrc/src/main/java/org/zaproxy/gradle/TaskException.java

Send repository dispatch to zaproxy to build the weekly Docker image
when the weekly is released.
Renamed `update-website` workflow to `handle-release` to match/include
the new behaviour.

Release weekly Docker image on weekly release

---

.github/workflows/handle-release.yml
ZapVersions.xml

Correct the name of the action input (`depth` → `fetch-depth`).
Tweak the name of a step.
Touch one of the `ZapVersions.xml` files to trigger the workflow.

Fix Handle Release workflow

---

build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/HandleMainRelease.java

Send repository dispatch to zaproxy to build the main Docker images
(stable and bare) when the main version is released.

Release main Docker images on main release

---

ZapVersions-2.10.xml
ZapVersions-2.7.xml
ZapVersions-2.8.xml
ZapVersions-2.9.xml
ZapVersions-dev.xml

The add-on has issues and is no longer properly maintained.
Part of zaproxy/zaproxy#6364.

Remove VulnCheck add-on

---

ZapVersions-2.10.xml
ZapVersions-dev.xml

Release version 28 of MacOS WebDrivers add-on.

webdrivermacos: release version 28

---

build.gradle.kts

Ensure copy of generated website data is done before replacing the
ZAP version (no file currently overlaps).

Order website tasks

---

files/news/2_10.xml
files/news/dev.xml

It _is_ news but also its a good way to get rid of the AMA news item which is now too late - someones already told me they signed up by mistake this morning ;)
Should not be merged until https://github.com/zaproxy/zaproxy.github.io/pull/343 is also merged (just needs one more approval;)

News: Report competition extended

---

src/main/crowdin-tasks.yml

Run `spotlessApply` after copying the localized resources, some add-ons
enforce the format.

Format localized resources in zap-extensions

---

.github/workflows/update-add-on-release.yml
.github/workflows/update-daily-release.yml
.github/workflows/update-main-release.yml

Do not persist the default credentials in release workflows as it's
causing a conflict with JGit (which should be using zapbot credentials).

Don't persist credentials in release workflows

---

src/main/addons-help-website.txt

Add the add-on ID to the list of included add-ons to generate the
website pages when the add-on is released.

Include Retest add-on for website help pages

---

src/main/java/org/zaproxy/admin/GenerateReleaseNotes.java

Obtain only the closed issues when generating the release notes, for
when the release notes are generated before all issues are closed.

Use only closed issues for release notes

---

build.gradle.kts

The daily releases check ZapVersions-dev file only.
Keep updating ZapVersions as it might be used by 3rd parties.
---
Per comments in #632.

Update daily release only on ZapVersions and dev

---

ZapVersions-2.11.xml
ZapVersions-dev.xml

chore: httpsinfo & tlsdebug: Remove add-ons being retired

---

src/main/addons-help-website.txt

Add `callhome` and remove `tlsdebug` and `httpsInfo`.

Update add-ons for website help pages

---

build.gradle.kts

Use the ZapVersions.xml file to extract the version of the daily
release, the file in use was no longer being updated with daily
releases causing the version in the commit message to be wrong.

Correct commit message for daily releases

---

.github/workflows/alert-docs.yml
scripts/generate_alert_pages.js

This will mean that we can run this script on a schedule and only get PRs if the details actually change.
Apart from the first run when all of the dates will go ;)

Remove date and lastmod fields from alert pages

---

buildSrc/src/main/java/org/zaproxy/gradle/website/Utils.java

Do not include the colon as it's not necessary for the add-on directory
when generating its help pages.

Remove colons from add-on dir name

---

ZapVersions-2.12.xml
ZapVersions-dev.xml

Remove the add-ons that were superseded by the Import/Export add-on:
- Import files containing URLs
- Log File Importer
- Save Raw Message
- Save XML Message

Remove superseded add-ons from dev/2.12

---

src/main/addons-help-website.txt

Noticed that the link to the database add-on help was broken in the ZAP 2.12.0 release blog post.
https://www.zaproxy.org/docs/desktop/addons/database/

Add database to add-on help publishing list

---

src/main/addons-help-website.txt

Add the add-on ID to the list of included add-ons to generate the website pages when the add-on is released.

Include Dev add-on for website help pages

---

ZapVersions-dev.xml
src/main/addons-help-website.txt

No longer make it available when running the weekly or source.
Remove from the website help generation.

Remove amf add-on from dev and website

---

.github/workflows/handle-release.yml

For cases where the website data needs to be regenerated without a release being done.

Allow to trigger the Handle Release workflow

---

.github/workflows/alert-docs.yml
.github/workflows/event-docs.yml

Signed-off-by: ricekot <github@ricekot.com>

Replace `hub` with `gh` in workflows

---

build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteSbomPages.java
buildSrc/src/main/java/org/zaproxy/gradle/TaskUtils.java
buildSrc/src/main/java/org/zaproxy/gradle/website/PageFrontMatter.java
buildSrc/src/main/java/org/zaproxy/gradle/website/WebsiteSbomPageGenerator.java

Related to https://github.com/zaproxy/zaproxy-website/pull/2183.

Generate add-on SBOM website pages on release

---

buildSrc/src/main/java/org/zaproxy/gradle/website/WebsiteSbomPageGenerator.java

Handle missing licenses and different type of license metadata.

Handle missing license in SBOMs

---

buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteSbomPages.java

Do not fail the task if not able to download the SBOM, not all add-ons might have it (e.g. third-party) and the SBOM is not critical for the website update.

Do not fail if not able to download the SBOM

---

ZapVersions-2.14.xml
ZapVersions-dev.xml

Use the blog post as info URL.

Reinstate `fileupload`'s info URL

---

ZapVersions-2.14.xml

Remove the add-on from the latest main release, the add-on has been retired a while ago (zaproxy/zap-extensions#4636).

Remove `amf` add-on

---

buildSrc/src/main/java/org/zaproxy/gradle/website/PageFrontMatter.java
buildSrc/src/main/java/org/zaproxy/gradle/website/WebsiteSbomPageGenerator.java

Ensure the components have a predictable order always.
Also, use a set to avoid listing duplicates.

Include SBOM components' version when sorting

---

ZapVersions-2.14.xml

The add-on is no longer in `zap-extensions`.

Remove repo from codedx

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/java/org/zaproxy/gradle/GenerateWebsiteSbomPages.java
buildSrc/src/main/java/org/zaproxy/gradle/SendRepositoryDispatch.java
buildSrc/src/main/java/org/zaproxy/gradle/TaskUtils.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateAddOnZapVersionsEntries.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateDailyZapVersionsEntries.java
buildSrc/src/main/java/org/zaproxy/gradle/UpdateMainZapVersionsEntries.java
buildSrc/src/main/java/org/zaproxy/gradle/website/Utils.java
buildSrc/src/main/java/org/zaproxy/gradle/website/WebsitePageGenerator.java

Build always with the Java version provided, as all the targeted versions are now supported.
Disable the lint `this-escape` to pass the compilation.
Address other warns.

Remove Java 11 requirement

---

scripts/generate_alert_pages.js

All of the links seem to work fine.
Tested with both active and passice script rules.
<details><summary>Screenshot</summary>
<p>
</p>
</details>

Handle script rules with metadata

---

ZapVersions-2.15.xml
ZapVersions-dev.xml
src/main/addons-help-website.txt

As per plan of discontinuing the portscan add-on, as better/specific tools exist.

Remove portscan

---

scripts/generate_alert_pages.js

`getExampleAlerts` is a public method for most scan rules and reflection is not needed to access it.
The reason this change was needed is that reflection was failing for `PassiveScriptScanRule`s. This is probably because we are using `ByteBuddy` to dynamically create a unique class for each passive script but I haven't checked in detail.
Without this change, many details are missing from the generated alert pages for passive scripts (e.g. see https://github.com/zaproxy/zaproxy-website/pull/2702).

Update generate_alert_pages.js script

---

ZapVersions-2.15.xml
ZapVersions-dev.xml

Release the following add-ons:
- Levo.ai version 0.3.0
Changes to the ZapVersions files were generated with the following commands:
```shell
export ADD_ON_DATA='{"addons":[{"checksum":"1a86d7c288bf4284e83f54203f4ed8
dd7d40b2bd47fbb8f8f853da67676269d2","url":"https://github.com/levoai/levoai-zap
-addon/releases/download/v0.3.0/levoai-zap-addon-alpha-0.3.0.zap"}]}'
./gradlew updateAndCreatePullRequestAddOnRelease --envVar=ADD_ON_DATA
```

Release Levo.ai add-on v0.3.0

---

src/main/addons-help-website.txt

Add the add-on ID to the list of included add-ons to generate the website pages when the add-on is released.

Include scanpolicies add-on for website help pages
